name: Deploy to Github Pages

# Run this workflow on every push to Main
on: [push]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish .NET 6 Project
        run: dotnet publish -c Release -o release --nologo
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 6.0
      - name: Change base.tag in index.html from / to ArashIzadiWebsiteGHP
        run: sed -i 's/<base href="\/" \/><base href="\/ArashIzadiGHP\/" \/>/g' release/wwwroot/index.html
      - name: Copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
      - name: Publish with dotnet
        run: dotnet publish --configuration Release --output build
      - name: Commit wwwroot to Github Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          FOLDER: build/wwwroot
          SINGLE_COMMIT: true

