name: Deploy to Github Pages

# Run this workflow on every push to Main
on: [push]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
